dist: bionic
language: csharp
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
language: csharp
mono: 5.16.0
# dotnet: 2.2.2

services:
  - docker

install: true

script:
- sudo snap alias dotnet-sdk.dotnet dotnet
- dotnet --version
- sudo ./build.sh
- echo "$DPWD" | docker login -u "$DUSR" --password-stdin
- docker build -t ptk .
- docker tag ptk:latest registry.heroku.com/ptk2/web
- docker login --username $HEROKU_DOCKER_USERNAME --password $HEROKU_AUTH_TOKEN registry.heroku.com
- docker push registry.heroku.com/ptk2/web
- sudo ./heroku-container-release.sh