language: csharp
#language: minimal
#solution: PTK.sln
sudo: required
mono: 5.16.0
dotnet: 2.1.4

services:
  - docker

before_install:
- sudo ./build.sh
- echo "$DPWD" | docker login -u "$DUSR" --password-stdin
- docker build -t ptk .
- docker tag ptk:latest registry.heroku.com/ptk2/web
- docker login --username $HEROKU_DOCKER_USERNAME --password $HEROKU_AUTH_TOKEN registry.heroku.com
- docker push registry.heroku.com/ptk2/web

# - docker pull carlad/sinatra
# - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
# - docker ps -a
# - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

#script:
# - bundle exec rake test

deploy:
  provider: heroku
  api_key:
    secure: "$HAPIK"
  app: ptk2